language: php
sudo: false
php:
  - 7.0
  - 7.1
notifications:
  email: false
before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer install
script:
  - vendor/bin/phpunit
